### ISSUE TITLE
Just a tidbit

### ISSUE THREAD

**Issue by blekmus** [yudhanjaya/xeffect#1]
Using local storage is severely underused. Most of the time when something can be solved by simply persisting it on the browser, you spend a bunch of resources sending everything to a server and keeping it close by for quick access again. Like, say you type something out halfway in a textbox. And if it's something long, like a note you're writing about a show you watched, you can't always finish it in one go. So rather than pasting it in Google Keeps or another note-taking app, if the application persists it in local storage, you can return to it whenever you want and continue. This is what Anilist does for all its inputs. For its twitter like statuses, comments and all forum posts. You can return to what you've written anytime you want, rather than having multiple tabs open at the same time.

**Comment by yudhanjaya** [comment]
Agreed. I use local storage here.  I'm moving to using local storage for my other side projects as well. A lot less hassle involved.

**Comment by yudhanjaya** [comment]
Not technically an issue.
